# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - blessed-sitecontainers-workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'blessed-sitecontainers-workflow'
  AZURE_WEBAPP_SLOT_NAME: 'Production'
  CONTAINER_REGISTRY: 'sitecontainerssampleacr.azurecr.io'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      # Steps to build and upload artifacts for python app.
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      

      - name: Create and start virtual environment
        working-directory: router-app
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: router-app
        run: |
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            router-app
            !router-app/venv/
      
      # Steps to build and push Sidecar container image to Azure Container Registry.
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container hello-app image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./hello-app
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/test/hello-app:${{ github.sha }}
          file: ./hello-app/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0DDBE8CA96F84EF68AA6DAEB2A817656 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF502E393C854DA1B23267120C36D934 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_196FB606BC0046998790AD6BF8BD6D7E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
          sitecontainers-config: >-
            [
              {
                "name": "hello-app",
                "image": "${{ env.CONTAINER_REGISTRY }}/test/hello-app:${{ github.sha }}",
                "targetPort": 5001,
                "isMain": false
              }
            ]